#include "src/game/envfx_snow.h"

const GeoLayout yoshi_egg_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(106383),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 150, 100),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, yoshi_egg_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, yoshi_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, yoshi_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, yoshi_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, yoshi_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, yoshi_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, yoshi_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, yoshi_egg_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, yoshi_egg_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
