extern const GeoLayout bobomb_buddy_geo[];
extern u8 bobomb_buddy_red_bombhei_ci8[];
extern u8 bobomb_buddy_red_bombhei_ci8_pal_rgba16[];
extern Vtx bobomb_buddy_skl_root_mesh_layer_4_vtx_0[36];
extern Gfx bobomb_buddy_skl_root_mesh_layer_4_tri_0[];
extern Vtx bobomb_buddy_displaylist_mesh_layer_4_vtx_0[4];
extern Gfx bobomb_buddy_displaylist_mesh_layer_4_tri_0[];
extern Vtx bobomb_buddy_foot_l1_mesh_layer_4_vtx_0[31];
extern Gfx bobomb_buddy_foot_l1_mesh_layer_4_tri_0[];
extern Vtx bobomb_buddy_foot_r1_mesh_layer_4_vtx_0[31];
extern Gfx bobomb_buddy_foot_r1_mesh_layer_4_tri_0[];
extern Gfx mat_bobomb_buddy_mat_red_bombhei_001_f3d[];
extern Gfx mat_revert_bobomb_buddy_mat_red_bombhei_001_f3d[];
extern Gfx bobomb_buddy_skl_root_mesh_layer_4[];
extern Gfx bobomb_buddy_displaylist_mesh_layer_4[];
extern Gfx bobomb_buddy_foot_l1_mesh_layer_4[];
extern Gfx bobomb_buddy_foot_r1_mesh_layer_4[];
extern Gfx bobomb_buddy_material_revert_render_settings[];
