#include "cheats.h"
#include "data/r96/r96_defines.h"
#include "pc/controller/controller_api.h"

struct CheatList Cheats;

struct CheatControls CheatsControls = {
    .TimeStopButton = { VK_INVALID, VK_INVALID, VK_INVALID },
    .SpambaControls = { 0x100D, 0x100E, 0x1009 }, // D-pad Left, D-pad Right, L trigger
};

const char **CheatJukeboxMusics[] = {

    // Musics
    &R96_LEVEL_BOB,
    &R96_LEVEL_WF,
    &R96_LEVEL_CCM,
    &R96_LEVEL_CCM_SLIDE,
    &R96_LEVEL_JRB_PHASE_1,
    &R96_LEVEL_JRB_PHASE_2,
    &R96_LEVEL_JRB_PHASE_3,
    &R96_LEVEL_JRB_SHIP,
    &R96_LEVEL_BBH_PHASE_1,
    &R96_LEVEL_BBH_PHASE_2,
    &R96_LEVEL_HMC_PHASE_1,
    &R96_LEVEL_HMC_PHASE_2,
    &R96_LEVEL_LLL_OUTSIDE,
    &R96_LEVEL_LLL_VOLCANO,
    &R96_LEVEL_SSL_OUTSIDE,
    &R96_LEVEL_SSL_PYRAMID,
    &R96_LEVEL_SSL_EYEROK,
    &R96_LEVEL_DDD_PHASE_1,
    &R96_LEVEL_DDD_PHASE_2,
    &R96_LEVEL_DDD_PHASE_3,
    &R96_LEVEL_SL_OUTSIDE,
    &R96_LEVEL_SL_IGLOO,
    &R96_LEVEL_WDW_MAIN,
    &R96_LEVEL_WDW_TOWN,
    &R96_LEVEL_TTM_OUTSIDE,
    &R96_LEVEL_TTM_SLIDE,
    &R96_LEVEL_THI_HUGE,
    &R96_LEVEL_THI_TINY,
    &R96_LEVEL_THI_WIGGLER,
    &R96_LEVEL_TTC,
    &R96_LEVEL_RR,
    &R96_LEVEL_BITDW,
    &R96_LEVEL_BITFS,
    &R96_LEVEL_BITS,
    &R96_LEVEL_SA,
    &R96_LEVEL_WMOTR,
    &R96_LEVEL_PSS,
    &R96_LEVEL_COTMC,
    &R96_LEVEL_TOTWC,
    &R96_LEVEL_VCUTM,
    &R96_LEVEL_BOWSER_1,
    &R96_LEVEL_BOWSER_2,
    &R96_LEVEL_BOWSER_3,
    &R96_LEVEL_INSIDE_CASTLE_LOBBY,
    &R96_LEVEL_INSIDE_CASTLE_TIPPY,
    &R96_LEVEL_INSIDE_CASTLE_BASEMENT,
    &R96_LEVEL_CASTLE_GROUNDS,
    &R96_LEVEL_CASTLE_COURTYARD,
    &R96_EVENT_CAP_WING,
    &R96_EVENT_CAP_VANISH,
    &R96_EVENT_CAP_METAL,
    &R96_EVENT_SHELL,
    &R96_EVENT_RACE,
    &R96_EVENT_BOSS_INTRO,
    &R96_EVENT_BOSS_THEME,
    &R96_EVENT_GOT_MILK,

    // Jingles
    &R96_EVENT_TITLE_SCREEN,
    &R96_MENU_FILE_SELECT,
    &R96_EVENT_PIRANHA_PLANT,
    &R96_EVENT_MERRY_GO_ROUND,
    &R96_EVENT_ENDLESS_STAIRS,
};
