name: Bug report
description: Report bugs with the mod itself.
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: dropdown
    id: modding
    attributes:
      label: "Are you building manually or with Builder2?"
      options:
        - Builder2
        - Manually
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Windows"
        - "Linux"
        - "Mac"
    validations:
      required: true
