name: Feature Request
description: Ask for a feature or just give ideas!
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the mod itself?
    validations:
      required: true
