name: Help me!
description: If you need help with the mod.
labels: [help wanted]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your problem here."
    validations:
      required: true

  - type: dropdown
    id: modding
    attributes:
      label: "Are you building manually or with Builder2?"
      options:
        - Builder2
        - Manually
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Windows x64"
        - "Windows x86/x32"
        - "Linux"
    validations:
      required: true