#include "src/game/envfx_snow.h"

const GeoLayout king_bobomb_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 300),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 750, 0, king_bobomb_body_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, -750, 0, king_bobomb_eye_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, king_bobomb_oukan_mesh_layer_4),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, -750, 0, king_bobomb_hige_mesh_layer_4),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 219, -313, 0, 0, 92, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, king_bobomb_sune_l_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, king_bobomb_asi_l_skinned_mesh_layer_4),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -1, -156, 19, 0, 178, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, king_bobomb_asi_l_mesh_layer_4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -219, -313, 0, 0, 88, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, king_bobomb_sune_r_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, king_bobomb_asi_r_skinned_mesh_layer_4),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -1, -156, -19, 0, -178, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, king_bobomb_asi_r_mesh_layer_4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 750, 0, king_bobomb_kata_l_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, king_bobomb_hand_l_1_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 615, 0, 0, king_bobomb_hand_l_1_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_update_held_mario_pos),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 750, 0, king_bobomb_kata_r_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, king_bobomb_hand_r_1_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, -615, 0, 0, king_bobomb_hand_r_1_mesh_layer_4),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, king_bobomb_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, king_bobomb_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
