#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"
#include "levels/rec_room/areas/1/collision.inc.c"
#include "levels/rec_room/areas/1/macro.inc.c"
#include "levels/rec_room/areas/1/spline.inc.c"
#include "levels/rec_room/texture.inc.c"
#include "levels/rec_room/areas/1/model.inc.c"
#include "levels/rec_room/areas/1/painting.inc.c"

#include "make_const_nonconst.h"