extern const GeoLayout bowling_ball_geo[];
extern const GeoLayout bowling_ball_track_geo[];
extern Lights1 bowling_ball_f3d_material_003_lights;
extern u8 ds_BlackBobBody_rgba32[];
extern Vtx bowling_ball_000_displaylist_mesh_layer_4_vtx_0[6];
extern Gfx bowling_ball_000_displaylist_mesh_layer_4_tri_0[];
extern Gfx mat_bowling_ball_f3d_material_003[];
extern Gfx mat_revert_bowling_ball_f3d_material_003[];
extern Gfx mat_BlackBobBody_f3d_material_003[];
extern Gfx mat_revert_BlackBobBody_f3d_material_003[];
extern Gfx bowling_ball_000_displaylist_mesh_layer_4[];
extern Gfx BlackBobBody_000_displaylist_mesh_layer_4[];
extern Gfx bowling_ball_material_revert_render_settings[];
