#ifndef CHEATS_MENU_H
#define CHEATS_MENU_H

#include "text/text-loader.h"

static const u8 optsPlayAsCheatStr[][32] = {
    "TEXT_OPT_PA1",
    "TEXT_OPT_PA2",
    "TEXT_OPT_PA3",
    "TEXT_OPT_PA4",
    "TEXT_OPT_PA5",
    "TEXT_OPT_PA6",
    "TEXT_OPT_PA7",
    "TEXT_OPT_PA8",
};

static const u8* PlayAsCheatChoices[] = {
    optsPlayAsCheatStr[0],
    optsPlayAsCheatStr[1],
    optsPlayAsCheatStr[2],
    optsPlayAsCheatStr[3],
    optsPlayAsCheatStr[4],
    optsPlayAsCheatStr[5],
    optsPlayAsCheatStr[6],
    optsPlayAsCheatStr[7],
};

static const u8 optsBLJCheatStr[][32] = {
    "TEXT_OPT_BLJCHT1",
    "TEXT_OPT_BLJCHT2",
    "TEXT_OPT_BLJCHT3",
    "TEXT_OPT_BLJCHT4",
    "TEXT_OPT_BLJCHT5",
    "TEXT_OPT_BLJCHT6",
    "TEXT_OPT_BLJCHT7",
    "TEXT_OPT_BLJCHT8",
    "TEXT_OPT_BLJCHT9",
    "TEXT_OPT_BLJCHT10",
    "TEXT_OPT_BLJCHT11",
    "TEXT_OPT_BLJCHT12",
    "TEXT_OPT_BLJCHT13",
};

static const u8* bljCheatChoices[] = {
    optsBLJCheatStr[0],
    optsBLJCheatStr[1],
    optsBLJCheatStr[2],
    optsBLJCheatStr[3],
    optsBLJCheatStr[4],
    optsBLJCheatStr[5],
    optsBLJCheatStr[6],
    optsBLJCheatStr[7],
    optsBLJCheatStr[8],
    optsBLJCheatStr[9],
    optsBLJCheatStr[10],
    optsBLJCheatStr[11],
    optsBLJCheatStr[12],
};

static const u8 optsCheatsModifierStrings[][64] = {
    "TEXT_OPT_CHEAT_MODIFIER_X1",
    "TEXT_OPT_CHEAT_MODIFIER_X2",
    "TEXT_OPT_CHEAT_MODIFIER_X3",
    "TEXT_OPT_CHEAT_MODIFIER_X4",
    "TEXT_OPT_CHEAT_MODIFIER_X5",
};

static const u8* optsCheatsModifierChoices[] = {
    optsCheatsModifierStrings[0],
    optsCheatsModifierStrings[1],
    optsCheatsModifierStrings[2],
    optsCheatsModifierStrings[3],
    optsCheatsModifierStrings[4],
};

static const u8 optsCheatsSizeStrings[][64] = {
    "TEXT_OPT_CHEAT_SIZE_X1",
    "TEXT_OPT_CHEAT_SIZE_X2",
    "TEXT_OPT_CHEAT_SIZE_X3",
    "TEXT_OPT_CHEAT_SIZE_X4",
    "TEXT_OPT_CHEAT_SIZE_X0",
    "TEXT_OPT_CHEAT_SIZE_X0_25",
    "TEXT_OPT_CHEAT_SIZE_X0_5",
    "TEXT_OPT_CHEAT_SIZE_X0_75",
};

static const u8* optsCheatsSizeChoices[] = {
    optsCheatsSizeStrings[0],
    optsCheatsSizeStrings[1],
    optsCheatsSizeStrings[2],
    optsCheatsSizeStrings[3],
    optsCheatsSizeStrings[4],
    optsCheatsSizeStrings[5],
    optsCheatsSizeStrings[6],
    optsCheatsSizeStrings[7],
};

static const u8 optsCheatsHurtStrings[][64] = {
    "TEXT_OPT_CHEAT_HURT_DISABLED",
    "TEXT_OPT_CHEAT_HURT_KNOCKBACK",
    "TEXT_OPT_CHEAT_HURT_SHOCK",
    "TEXT_OPT_CHEAT_HURT_BURN",
    "TEXT_OPT_CHEAT_HURT_LAVA_BOOST",
    "TEXT_OPT_CHEAT_HURT_SQUISH",
    "TEXT_OPT_CHEAT_HURT_STUCK",
    "TEXT_OPT_CHEAT_HURT_1_HP",
};

static const u8* optsCheatsHurtChoices[] = {
    optsCheatsHurtStrings[0],
    optsCheatsHurtStrings[1],
    optsCheatsHurtStrings[2],
    optsCheatsHurtStrings[3],
    optsCheatsHurtStrings[4],
    optsCheatsHurtStrings[5],
    optsCheatsHurtStrings[6],
    optsCheatsHurtStrings[7],
};

static const u8 optsCheatsWaterLevelStrings[][64] = {
    "TEXT_OPT_CHEAT_WATER_LEVEL_DEFAULT",
    "TEXT_OPT_CHEAT_WATER_LEVEL_DRAINED",
    "TEXT_OPT_CHEAT_WATER_LEVEL_FLOODED",
};

static const u8* optsCheatsWaterLevelChoices[] = {
    optsCheatsWaterLevelStrings[0],
    optsCheatsWaterLevelStrings[1],
    optsCheatsWaterLevelStrings[2],
};

static const u8 optsCheatsJukeboxStrings[][64] = {
    "TEXT_OPT_CHEAT_JUKEBOX_BOB",
    "TEXT_OPT_CHEAT_JUKEBOX_WF",
    "TEXT_OPT_CHEAT_JUKEBOX_CCM",
    "TEXT_OPT_CHEAT_JUKEBOX_CCM_SLIDE",
    "TEXT_OPT_CHEAT_JUKEBOX_JRB_PHASE_1",
    "TEXT_OPT_CHEAT_JUKEBOX_JRB_PHASE_2",
    "TEXT_OPT_CHEAT_JUKEBOX_JRB_PHASE_3",
    "TEXT_OPT_CHEAT_JUKEBOX_JRB_SHIP",
    "TEXT_OPT_CHEAT_JUKEBOX_BBH_PHASE_1",
    "TEXT_OPT_CHEAT_JUKEBOX_BBH_PHASE_2",
    "TEXT_OPT_CHEAT_JUKEBOX_HMC_PHASE_1",
    "TEXT_OPT_CHEAT_JUKEBOX_HMC_PHASE_2",
    "TEXT_OPT_CHEAT_JUKEBOX_LLL_OUTSIDE",
    "TEXT_OPT_CHEAT_JUKEBOX_LLL_VOLCANO",
    "TEXT_OPT_CHEAT_JUKEBOX_SSL_OUTSIDE",
    "TEXT_OPT_CHEAT_JUKEBOX_SSL_PYRAMID",
    "TEXT_OPT_CHEAT_JUKEBOX_SSL_EYEROK",
    "TEXT_OPT_CHEAT_JUKEBOX_DDD_PHASE_1",
    "TEXT_OPT_CHEAT_JUKEBOX_DDD_PHASE_2",
    "TEXT_OPT_CHEAT_JUKEBOX_DDD_PHASE_3",
    "TEXT_OPT_CHEAT_JUKEBOX_SL_OUTSIDE",
    "TEXT_OPT_CHEAT_JUKEBOX_SL_IGLOO",
    "TEXT_OPT_CHEAT_JUKEBOX_WDW_MAIN",
    "TEXT_OPT_CHEAT_JUKEBOX_WDW_TOWN",
    "TEXT_OPT_CHEAT_JUKEBOX_TTM_OUTSIDE",
    "TEXT_OPT_CHEAT_JUKEBOX_TTM_SLIDE",
    "TEXT_OPT_CHEAT_JUKEBOX_THI_HUGE",
    "TEXT_OPT_CHEAT_JUKEBOX_THI_TINY",
    "TEXT_OPT_CHEAT_JUKEBOX_THI_WIGGLER",
    "TEXT_OPT_CHEAT_JUKEBOX_TTC",
    "TEXT_OPT_CHEAT_JUKEBOX_RR",
    "TEXT_OPT_CHEAT_JUKEBOX_BITDW",
    "TEXT_OPT_CHEAT_JUKEBOX_BITFS",
    "TEXT_OPT_CHEAT_JUKEBOX_BITS",
    "TEXT_OPT_CHEAT_JUKEBOX_SA",
    "TEXT_OPT_CHEAT_JUKEBOX_WMOTR",
    "TEXT_OPT_CHEAT_JUKEBOX_PSS",
    "TEXT_OPT_CHEAT_JUKEBOX_COTMC",
    "TEXT_OPT_CHEAT_JUKEBOX_TOTWC",
    "TEXT_OPT_CHEAT_JUKEBOX_VCUTM",
    "TEXT_OPT_CHEAT_JUKEBOX_BOWSER_1",
    "TEXT_OPT_CHEAT_JUKEBOX_BOWSER_2",
    "TEXT_OPT_CHEAT_JUKEBOX_BOWSER_3",
    "TEXT_OPT_CHEAT_JUKEBOX_INSIDE_CASTLE_LOBBY",
    "TEXT_OPT_CHEAT_JUKEBOX_INSIDE_CASTLE_TIPPY",
    "TEXT_OPT_CHEAT_JUKEBOX_INSIDE_CASTLE_BASEMENT",
    "TEXT_OPT_CHEAT_JUKEBOX_CASTLE_GROUNDS",
    "TEXT_OPT_CHEAT_JUKEBOX_CASTLE_COURTYARD",
    "TEXT_OPT_CHEAT_JUKEBOX_CAP_WING",
    "TEXT_OPT_CHEAT_JUKEBOX_CAP_VANISH",
    "TEXT_OPT_CHEAT_JUKEBOX_CAP_METAL",
    "TEXT_OPT_CHEAT_JUKEBOX_SHELL",
    "TEXT_OPT_CHEAT_JUKEBOX_RACE",
    "TEXT_OPT_CHEAT_JUKEBOX_BOSS_INTRO",
    "TEXT_OPT_CHEAT_JUKEBOX_BOSS_THEME",
    "TEXT_OPT_CHEAT_JUKEBOX_GOT_MILK",
    "TEXT_OPT_CHEAT_JUKEBOX_TITLE_SCREEN",
    "TEXT_OPT_CHEAT_JUKEBOX_FILE_SELECT",
    "TEXT_OPT_CHEAT_JUKEBOX_PIRANHA_PLANT",
    "TEXT_OPT_CHEAT_JUKEBOX_MERRY_GO_ROUND",
    "TEXT_OPT_CHEAT_JUKEBOX_ENDLESS_STAIRS",
};

static const u8* optsCheatsJukeboxChoices[] = {
    optsCheatsJukeboxStrings[0],
    optsCheatsJukeboxStrings[1],
    optsCheatsJukeboxStrings[2],
    optsCheatsJukeboxStrings[3],
    optsCheatsJukeboxStrings[4],
    optsCheatsJukeboxStrings[5],
    optsCheatsJukeboxStrings[6],
    optsCheatsJukeboxStrings[7],
    optsCheatsJukeboxStrings[8],
    optsCheatsJukeboxStrings[9],
    optsCheatsJukeboxStrings[10],
    optsCheatsJukeboxStrings[11],
    optsCheatsJukeboxStrings[12],
    optsCheatsJukeboxStrings[13],
    optsCheatsJukeboxStrings[14],
    optsCheatsJukeboxStrings[15],
    optsCheatsJukeboxStrings[16],
    optsCheatsJukeboxStrings[17],
    optsCheatsJukeboxStrings[18],
    optsCheatsJukeboxStrings[19],
    optsCheatsJukeboxStrings[20],
    optsCheatsJukeboxStrings[21],
    optsCheatsJukeboxStrings[22],
    optsCheatsJukeboxStrings[23],
    optsCheatsJukeboxStrings[24],
    optsCheatsJukeboxStrings[25],
    optsCheatsJukeboxStrings[26],
    optsCheatsJukeboxStrings[27],
    optsCheatsJukeboxStrings[28],
    optsCheatsJukeboxStrings[29],
    optsCheatsJukeboxStrings[30],
    optsCheatsJukeboxStrings[31],
    optsCheatsJukeboxStrings[32],
    optsCheatsJukeboxStrings[33],
    optsCheatsJukeboxStrings[34],
    optsCheatsJukeboxStrings[35],
    optsCheatsJukeboxStrings[36],
    optsCheatsJukeboxStrings[37],
    optsCheatsJukeboxStrings[38],
    optsCheatsJukeboxStrings[39],
    optsCheatsJukeboxStrings[40],
    optsCheatsJukeboxStrings[41],
    optsCheatsJukeboxStrings[42],
    optsCheatsJukeboxStrings[43],
    optsCheatsJukeboxStrings[44],
    optsCheatsJukeboxStrings[45],
    optsCheatsJukeboxStrings[46],
    optsCheatsJukeboxStrings[47],
    optsCheatsJukeboxStrings[48],
    optsCheatsJukeboxStrings[49],
    optsCheatsJukeboxStrings[50],
    optsCheatsJukeboxStrings[51],
    optsCheatsJukeboxStrings[52],
    optsCheatsJukeboxStrings[53],
    optsCheatsJukeboxStrings[54],
    optsCheatsJukeboxStrings[55],
    optsCheatsJukeboxStrings[56],
    optsCheatsJukeboxStrings[57],
    optsCheatsJukeboxStrings[58],
    optsCheatsJukeboxStrings[59],
    optsCheatsJukeboxStrings[60],
    optsCheatsJukeboxStrings[61],
};

static const u8 optsCheatsBtnStrings[][64] = {
    "TEXT_BIND_TIME_STOP",
    "TEXT_BIND_SPAMBA_CONTROLS",
};

static const u8 optsCheatsCatStrings[][64] = {
    "TEXT_OPT_CHEAT_CATEGORY_CLASSIC_TITLE",
    "TEXT_OPT_CHEAT_CATEGORY_MODIFIERS_TITLE",
    "TEXT_OPT_CHEAT_CATEGORY_TIME_SPACE_TITLE",
    "TEXT_OPT_CHEAT_CATEGORY_CLASSIC_LABEL",
    "TEXT_OPT_CHEAT_CATEGORY_MODIFIERS_LABEL",
    "TEXT_OPT_CHEAT_CATEGORY_TIME_SPACE_LABEL",
    "TEXT_OPT_CHEAT_DISABLE_ALL_CHEATS",
};

static const u8 optsCheatsChtStrings[][64] = {
    "TEXT_OPT_CHEAT_ENABLE_CHEATS",
    "TEXT_OPT_CHEAT_SPAMBA",
    "TEXT_OPT_CHEAT_CHAOS_MODE",

    "TEXT_OPT_CHEAT_MOON_JUMP",
    "TEXT_OPT_CHEAT_GOD_MODE",
    "TEXT_OPT_CHEAT_INFINITE_LIVES",
    "TEXT_OPT_CHEAT_RESPONSIVE",
    "TEXT_OPT_CHEAT_MOON_GRAVITY",
    "TEXT_OPT_CHEAT_DEBUG_MOVE",
    "TEXT_OPT_CHEAT_SUPER_COPTER",
    "TEXT_OPT_CHEAT_AUTO_WALL_KICK",
    "TEXT_OPT_CHEAT_NO_HOLD_HEAVY",

    "TEXT_OPT_CHEAT_SPEED_MODIFIER",
    "TEXT_OPT_CHEAT_JUMP_MODIFIER",
    "TEXT_OPT_CHEAT_SWIM_MODIFIER",
    "TEXT_OPT_CHEAT_SIZE_MODIFIER",
    "TEXT_OPT_CHEAT_CAP_MODIFIER",
    "TEXT_OPT_CHEAT_SUPER_WING_CAP",
    "TEXT_OPT_CHEAT_PLAY_AS",
    "TEXT_OPT_CHEAT_JUKEBOX",
    "TEXT_OPT_CHEAT_JUKEBOX_MUSIC",
    "TEXT_OPT_CHEAT_SPEED_DISPLAY",
    
    "TEXT_OPT_CHEAT_BLJ_ANYWHERE",
    "TEXT_OPT_CHEAT_SWIM_ANYWHERE",
    "TEXT_OPT_CHEAT_EXIT_ANYWHERE",
    "TEXT_OPT_CHEAT_WALK_ON_HAZARDS",
    "TEXT_OPT_CHEAT_NO_DEATH_BARRIER",
    "TEXT_OPT_CHEAT_NO_BOUNDS",
    "TEXT_OPT_CHEAT_WATER_LEVEL",
    "TEXT_OPT_CHEAT_COINS_MAGNET",
    "TEXT_OPT_CHEAT_TIME_STOP",
    "TEXT_OPT_CHEAT_QUICK_ENDING",
    "TEXT_OPT_CHEAT_HURT_MARIO",
};

#endif // CHEATS_MENU_H
