#include "src/game/envfx_snow.h"

const GeoLayout bobomb_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 200, 85),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 19661),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, -4, 0, bobomb_skl_root_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, bobomb_displaylist_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, bobomb_foot_l1_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 56, 0, 0, bobomb_foot_l1_mesh_layer_4),
					GEO_DISPLAY_LIST(LAYER_ALPHA, bobomb_foot_r1_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, -56, 0, 0, bobomb_foot_r1_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, bobomb_spring_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bobomb_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
